name: Publish Common Modules

on:
  workflow_call:
    inputs:
      module_path:
        required: true
        type: string

jobs:
  deploy-common:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: temurin
      - name: Deploy to GitHub Packages
        run: |
          echo "<settings>
            <servers>
              <server>
                <id>github</id>
                <username>${{ github.actor }}</username>
                <password>${{ secrets.PACKAGE_PAT }}</password>
              </server>
            </servers>
          </settings>" > settings.xml
          cd ${{ inputs.module_path }}
          mvn clean deploy -s settings.xml
        env:
          PACKAGE_PAT: ${{ secrets.PACKAGE_PAT }}

      
