name: Publish Common Modules

on:
  workflow_call:
    inputs:
      module_path:
        required: true
        type: string
    secrets:
      PACKAGE_PAT:
        required: true

jobs:
  deploy-common:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: temurin
      - name: Deploy to GitHub Packages
        env:
          DEPLOY_TOKEN: ${{ secrets.PACKAGE_PAT }}
        run: |
          echo "<settings>
            <servers>
              <server>
                <id>github</id>
                <username>${{ github.actor }}</username>
                <password>${DEPLOY_TOKEN}</password>
              </server>
            </servers>
            <profiles>
              <profile>
                <id>github</id>
                <repositories>
                  <repository>
                    <id>github</id>
                    <url>https://maven.pkg.github.com/gescoes</url>
                  </repository>
                </repositories>
              </profile>
            </profiles>
            <activeProfiles>
              <activeProfile>github</activeProfile>
            </activeProfiles>
          </settings>" > settings.xml
          cd ${{ inputs.module_path }}
          mvn clean deploy -s settings.xml
