name: Publish Common Modules

on:
  workflow_call:
    inputs:
      module_path:
        required: true
        type: string

jobs:
  deploy-common:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: temurin
      - name: Deploy module to GitHub Packages
        run: |
          cd ${{ inputs.module_path }}
          mvn clean deploy
